config/routes.rb
Utcal::Application.routes.draw do

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help',    to: 'static_pages#help'
  match '/error',    to: 'static_pages#error', as: 'errors'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/assignments/studinfo', to: 'assignments#studinfo'
  match '/courses/builddb', to: 'courses#builddb'
  match '/admin/buildstudents', to: 'admin#buildstudents'
  match '/admin/buildcourses', to: 'admin#buildcourses'
  match '/admin/dashboard', to: 'admin#dashboard'
  match '/admin/buildprof', to: 'admin#buildprof' 

  get "/users/mycourselist" => "users#mycourselist"
  get "/users/mystudents_courses/:id", :to => "users#mystudents_courses", :as => "users_mystudents_courses"
  get "/users/mystudents/:id" => "courses#mystudents"
  get "/user/:id" => "professors#display"
  get "/user/:id" => "professors#buildDB"  #THIS IS FOR POPULATING COURSE TABLE
  get "/user/:id" => "courses#enrolledincourse" 
  get "/users/:id" => "professors#show" 
  get "/users/add/:id" => "professors#add_students"
  get "/assignments/courseasgns/:id" => "assignments#courseasgns" 

  
  post "/users/add/:id/mail_students" => "professors#mail_students"

  resources :admin

  resources :students

  resources :professors

  resources :courses

  resources :users

  resources :assignments

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/professor.rb
class Professor < ActiveRecord::Base
  attr_accessible :email, :f_name, :l_name, :user_id
 
  validates :user_id, presence: true
  validates :f_name,  length: { maximum: 50 }
  validates :l_name,  length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  #, uniqueness: { case_sensitive: false }

   belongs_to :user

   def to_param
   	user_id
   end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_filter :signed_in_user
  before_filter :correct_user
  # GET /professors
  # GET /professors.json

  def index
    @professors = Professor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @professors }
    end
  end

  # GET /professors/1
  # GET /professors/1.json

  def removeDupes(arr)
      @temp_arr =[]
      arr.each do |arr1|
        arr1.each do |arr2|
          @temp_arr.push(arr2)
        end  
      end
      @temp_arr
  end

  def addHashTag(courses)
    @tagged = []
    courses.each do |c|
      size = c.std_crs.length

      c.code = c.code + "#" + size.to_s
      @tagged.push(c.code)
    end
    @tagged
  end

  def removeAsgn(arr)
    @final = []
    arr.each do |u|
    c = @final.find_all {|e| e == u}.size
    lgth = arr.find_all {|e| e == u}.size
    x = u
    x.title = x.title + "(" +lgth.to_s()+")"
        @final.push(x) unless c > 0
    end
    @final  
  end



  def show


  
    @professor = Professor.find_by_user_id(params[:id])
      @courses = current_user.mycourses
      @course_tagged = addHashTag(@courses)
      @temp_tutorials = []
      @temp_students = []
      @temp_assignments = []
      @courses.each do |c|
        @temp_students.push(c.std_crs)
        @temp_tutorials.push(c.getTutorials)
        @temp_assignments.push(c.get_assignments)
      end
      @students = removeDupes(@temp_students)
      @assign_t = removeDupes(@temp_assignments)
      @assignments = removeAsgn(@assign_t)
      @tutorials = removeDupes(@temp_tutorials)

      #get all tutorials and practicals
      

      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => {:professor => @professor, :courses => @course_tagged,
                                       :tutorials => @tutorials}}
      
      end
   
  end

  # GET /professors/new
  # GET /professors/new.json
  def new
    @professor = Professor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @professor }
    end


  end

  # GET /professors/1/edit
  def edit
    @professor = Professor.find_by_user_id(params[:id])
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(params[:professor])

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render json: @professor, status: :created, location: @professor }
      else
        format.html { render action: "new" }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /professors/1
  # PUT /professors/1.json
  def update
    @professor = Professor.find_by_user_id(params[:id])

    respond_to do |format|
      if @professor.update_attributes(params[:professor])
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor = Professor.find_by_user_id(params[:id])
    @professor.destroy

    respond_to do |format|
      format.html { redirect_to professors_url }
      format.json { head :no_content }
    end
  end

  def add_students
    @professor = Professor.find_by_user_id(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @professor }
    end
  end

  def mail_students
    @professor = Professor.find_by_user_id(params[:id])
    @all_emails = params[:emadds]

    respond_to do |format|
      email = @all_emails.split(",").map(&:strip).reject(&:empty?)

      student_mailer.sign_to_courses(@professor, email).deliver
      format.html
      format.json {render json: @professor}
   end 

  end




  private
    def signed_in_user
      redirect_to signin_url, notice: "Please sign in" unless signed_in?
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end



end

app/helpers/professors_helper.rb
module ProfessorsHelper



end

app/views/professors/_form.html.erb
<%= form_for(@professor) do |f| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% @professor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :f_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :l_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/professors/add_students.html.erb
<p> ADD STUDENTS </p>

<%=  form_tag(@professor.id.to_s+"/mail_students", :method => "post") do%>
  <%= label_tag(:emadds, "Add student Emails")%>
  <%= text_field_tag(:emadds) %>
  <%= submit_tag("Send Request")%>
<% end %>

app/views/professors/buildcourses.html.erb
<h6>XML OUTPUT OF THE CSV</h6>
<%= @c %>

app/views/professors/display.html.erb
<script type="text/javascript">
$(document).ready(function(){
	$("#calendar").fullCalendar({
		header: {
			left: 'prev, next today',
			middle: 'title',
			right: 'agendaWeek'
		},
		defaultView: 'agendaWeek',
		editable: false,
		slotMinutes: 60,
		minTime: 9,
		maxTime: 23
	})
});
</script>

<div id='calendar'></div>

app/views/professors/edit.html.erb
<h1>Editing professor</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @professor %><!-- |
<%= link_to 'Back', professors_path %> -->

app/views/professors/index.html.erb
<h1>Listing professors</h1>

<table>
  <tr>
    <th>F name</th>
    <th>L name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @professors.each do |professor| %>
  <tr>
    <td><%= professor.f_name %></td>
    <td><%= professor.l_name %></td>
    <td><%= professor.email %></td>
  
    <td><%= link_to 'Show', professor %></td>
    <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
    <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/mail_students.html.erb
<p> check your email </p>

app/views/professors/new.html.erb
<h1>New professor</h1>

<%= render 'form' %>

<!-- <%= link_to 'Back', professors_path %> -->

app/views/professors/profassgns.html.erb
<h1> Prof Assignments </h1>
<p><%= @get_assgns %></p>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<%= javascript_include_tag "calendarBuilder.js" %>
<script type="text/javascript">
	var set = 0;
        <% @courses.each do |course| %>
        <% course.start = course.start.to_time.to_i %>
        <% course.end = course.end.to_time.to_i %>
        <%end%>
        <% @assignments.each do |ass| %>
        <% ass.start = ass.start.to_time.to_i %>
        <% ass.end = ass.end.to_time.to_i %>
	<%end%>
        var coursesToJSON = <%= raw @courses.to_json %>
        var assignmentsToJSON = <%= raw @assignments.to_json %>
	<% ht = Hash.new%>	
	<% @assignments.each do |ass|%>
	<% ht[ass.id] = ass.courses.first %>
	<% end %>
	var atoc = <%= raw ht.to_json %>
        $(document).ready(function(){

        buildCalendar(coursesToJSON, assignmentsToJSON);

        });
  
        document.addEventListener("DOMSubtreeModified", function(e){
                if($(e.target).attr("class") == "fc-event fc-event-skin fc-event-vert fc-corner-top fc-corner-bottom"){
			var node = $(e.target).find(".fc-event-title");
			if (!node.has("div").length){
				var curr = node.text();
				node.empty();
				node.html("<div style='display:none'>"+curr.split("#")[1]+"</div>" + curr.split("#")[0]);	
			}
		}
		if($(".fc-event")[0] && set == 0){
                        setHover(assignmentsToJSON, coursesToJSON, atoc);
                        set = 1;
                }if(!$(".fc-event")[0]){
                        set = 0;
                }
        });
</script>

<p >Check schedule for: </p>
<% courseList = [] %>
<% @courses.each do |course| %>
<% if(courseList.index(course.code) == nil)%>
	<% courseList.push(course.code) %>
	<div style="margin-right:6px; float:left;text-decoration:none;"><%= link_to course.code, users_mystudents_courses_path(course.id) %></div>
<%end%>
<%end%>
<br />
<br />
<div id='calendar'></div>

<p class="test">
  <b>First name:</b>
  <%= @professor.f_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @professor.l_name %>	
</p>

<p>
<b> List of courses </b>
 <%= @course %>  

</p>

<%= link_to 'Edit', edit_professor_path(@professor) %><!-- |
<%= link_to 'Back', professors_path %> -->