config/routes.rb
Utcal::Application.routes.draw do

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help',    to: 'static_pages#help'
  match '/error',    to: 'static_pages#error', as: 'errors'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/assignments/studinfo', to: 'assignments#studinfo'
  match '/courses/builddb', to: 'courses#builddb'
  match '/admin/buildstudents', to: 'admin#buildstudents'
  match '/admin/buildcourses', to: 'admin#buildcourses'
  match '/admin/dashboard', to: 'admin#dashboard'
  match '/admin/buildprof', to: 'admin#buildprof' 

  get "/users/mycourselist" => "users#mycourselist"
  get "/users/mystudents_courses/:id", :to => "users#mystudents_courses", :as => "users_mystudents_courses"
  get "/users/mystudents/:id" => "courses#mystudents"
  get "/user/:id" => "professors#display"
  get "/user/:id" => "professors#buildDB"  #THIS IS FOR POPULATING COURSE TABLE
  get "/user/:id" => "courses#enrolledincourse" 
  get "/users/:id" => "professors#show" 
  get "/users/add/:id" => "professors#add_students"
  get "/assignments/courseasgns/:id" => "assignments#courseasgns" 

  
  post "/users/add/:id/mail_students" => "professors#mail_students"

  resources :admin

  resources :students

  resources :professors

  resources :courses

  resources :users

  resources :assignments

  resources :sessions, only: [:new, :create, :destroy]

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  # XMLDIR = "/home/ather/Desktop/Project/utcal/utcal/CourseTimetable.xml"
  XMLDIR = "/home/zieny/rubyProject/utcal/CourseTimetable.xml"

  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        # current_user.courses.concat(@course)
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  def mystudents
    course = Course.find(params[:id])
    @list = course.enrolledincourse
    render 'mystudents'
  end

  def courselist
    @courses = Course.find(:all)
    render 'courselist'


end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :section %><br />
    <%= f.text_field :section %>
  </div>
  <div class="field">
    <%= f.label :restrictions %><br />
    <%= f.text_field :restrictions %>
  </div>
  <div class="field">
    <%= f.label :days %><br />
    <%= f.text_field :days %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.time_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.time_select :end %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/build.html.erb
<h6>XML OUTPUT OF THE CSV</h6>
<%= @c %>

app/views/courses/builddb.html.erb
<h6>XML OUTPUT OF THE CSV</h6>
 <%=  @c %>

app/views/courses/courselist.html.erb
<!-- <%= @allcourses %> -->
<% @allcourses.each do |crs| %>
    <label><%= radio_button_tag "course_id", crs.id, @allcourses.include?(crs) %> <%= crs.code %>, <%= crs.meeting %></label>
<% end %> 
<%= submit_tag("Submit", :onclick => "/admin/joy") %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Section</th>
    <th>Restrictions</th>
    <th>Days</th>
    <th>Start</th>
    <th>End</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.code %></td>
    <td><%= course.section %></td>
    <td><%= course.restrictions %></td>
    <td><%= course.days %></td>
    <td><%= course.start %></td>
    <td><%= course.end %></td>
    <td><%= course.location %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/mystudents.html.erb
<%= @list %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @course.code %>
</p>

<p>
  <b>Section:</b>
  <%= @course.section %>
</p>

<p>
  <b>Restrictions:</b>
  <%= @course.restrictions %>
</p>

<p>
  <b>Days:</b>
  <%= @course.days %>
</p>

<p>
  <b>Start:</b>
  <%= @course.start %>
</p>

<p>
  <b>End:</b>
  <%= @course.end %>
</p>

<p>
  <b>Location:</b>
  <%= @course.location %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>