config/routes.rb
Utcal::Application.routes.draw do

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help',    to: 'static_pages#help'
  match '/error',    to: 'static_pages#error', as: 'errors'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/assignments/studinfo', to: 'assignments#studinfo'
  match '/courses/builddb', to: 'courses#builddb'
  match '/admin/buildstudents', to: 'admin#buildstudents'
  match '/admin/buildcourses', to: 'admin#buildcourses'
  match '/admin/dashboard', to: 'admin#dashboard'
  match '/admin/buildprof', to: 'admin#buildprof' 

  get "/users/mycourselist" => "users#mycourselist"
  get "/users/mystudents_courses/:id", :to => "users#mystudents_courses", :as => "users_mystudents_courses"
  get "/users/mystudents/:id" => "courses#mystudents"
  get "/user/:id" => "professors#display"
  get "/user/:id" => "professors#buildDB"  #THIS IS FOR POPULATING COURSE TABLE
  get "/user/:id" => "courses#enrolledincourse" 
  get "/users/:id" => "professors#show" 
  get "/users/add/:id" => "professors#add_students"
  get "/assignments/courseasgns/:id" => "assignments#courseasgns" 

  
  post "/users/add/:id/mail_students" => "professors#mail_students"

  resources :admin

  resources :students

  resources :professors

  resources :courses

  resources :users

  resources :assignments

  resources :sessions, only: [:new, :create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    UofT Calendar and Schedule Manager
  </small>
  <nav>
    <br />
    <p class='notice'><%= notice %></p>
    <p class='alert'> <%= alert %></p>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><a href="http://www.utsc.utoronto.ca/aboutUs/contacts.html">Contacts</a></li>
      <li><a href="http://www.utsc.utoronto.ca">UTSC</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
   <header class='navbar navbar-fixed-top navbar-inverse'> 
      <div class='navbar-inner'>   
        <div class="pageWidth container">
          <%= link_to "UofT Calendar", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",   root_path %></li>
              <li><%= link_to "Help",    help_path %></li>

              <% if signed_in? %>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">

                    <% if signed_student? %>
                      <li><%= link_to signed_type, Professor.find_by_user_id(session[:remember_token])%></li>
                    <% else %>
                      <li><%= link_to signed_type, Student.find_by_user_id(session[:remember_token]) %></li>
                    <% end %>
                    <!-- <li><%= link_to "Settings", '#' %></li> -->
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Sign out", signout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UofT Calander | <%= yield(:title) %></title>
    <%= stylesheet_link_tag 'fullcalendar.css' %>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "jquery-ui-1.8.11.custom.min.js" %>
    <%= javascript_include_tag "fullcalendar.js" %>
    <%= javascript_include_tag "calendar.js" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="pageWidth container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <br />
      <br />
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/backup.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>